FROM diceunc/dataone-indexer:4.2.1.0

ENV CONSUL_TEMPLATE_BASE=https://releases.hashicorp.com/consul-template
ENV CONSUL_TEMPLATE_VERSION=0.16.0
ENV CONSUL_TEMPLATE_SHA256SUM=064b0b492bb7ca3663811d297436a4bbf3226de706d2b76adade7021cd22e156
ENV CONSUL_TEMPLATE_FILE=consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip

ADD ${CONSUL_TEMPLATE_BASE}/${CONSUL_TEMPLATE_VERSION}/${CONSUL_TEMPLATE_FILE} .

RUN echo "${CONSUL_TEMPLATE_SHA256SUM}  ${CONSUL_TEMPLATE_FILE}" | sha256sum -c - \
    && unzip ${CONSUL_TEMPLATE_FILE} \
    && mkdir -p /usr/local/bin \
    && mv consul-template /usr/local/bin/consul-template

COPY consul.hcl /
COPY d1client.properties.tmpl /
COPY default-event-indexer.properties.tmpl /
COPY generate-configs.sh /usr/local/bin/
COPY run-event-indexer.sh /usr/local/bin/

CMD ["run-event-indexer.sh"]
